### PR TITLE
[ENG-54011] [Automation] R&D GH Web Automation (Web Login)

### PR DESCRIPTION
**Pull request by GOlmillaPM**
- Cleaned up repository
- Added keywords for Greenhouse Web login

Staging:
image
image

UAT:
image
image

### CODE REVIEW

**Review by lorie143 — CHANGES_REQUESTED** [review]
Hello @GOlmillaPM  can we add the keys folder under resources? Guide in Dashboard web repo. Thanks!

**Comment by GOlmillaPM** [comment]
> Hello @GOlmillaPM can we add the keys folder under resources? Guide in Dashboard web repo. Thanks!

Hi, @lorie143! The keys folder already exists in the base folder upon creation since I used a template. :) Thank you!
Screenshot 2024-11-25 at 12 02 49 PM

**Review by lorie143 — APPROVED** [review]
Approved on my end, thanks!

**Review by jenimagpantay — CHANGES_REQUESTED** [review]

**Review by jenimagpantay — APPROVED** [review]
Approved

**Pull request merged**
